- name: copy configuration.yaml
  copy:
    src: configuration.yaml
    dest: config/configuration.yaml

- name: create {{ item }} dir
  file:
    path: config/{{ item }}
    state: directory
  with_items:
    - dashboards
    - automations
    - scripts
    - inputs

- include_tasks: satel.yml

- name: upload templates
  template:
    src: "{{ item }}.j2"
    dest: "config/{{ item }}"
  loop:
    - dashboards.yaml

- name: copy dashboards
  template:
    src: "{{ item }}"
    dest: "config/dashboards/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob: "{{ role_path }}/templates/dashboards/**.yaml.j2"
  tags: dashboards

- name: upload blueprints
  copy:
    src: "{{ item }}"
    dest: "config/blueprints/automation/{{ item | basename }}"
  with_fileglob: "{{ role_path }}/files/blueprints/**.yaml"
  tags: automations

- name: upload automations
  template:
    src: "{{ item }}"
    dest: "config/automations/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob: "{{ role_path }}/templates/automations/**.yaml.j2"
  tags: automations

- name: upload scripts
  template:
    src: "{{ item }}"
    dest: "config/scripts/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob: "{{ role_path }}/templates/scripts/**.yaml.j2"
  tags: scripts

- name: upload inputs
  copy:
    src: "{{ item }}"
    dest: "config/inputs/{{ item | basename }}"
  with_fileglob: "{{ role_path }}/files/inputs/**.yaml"
  tags: inputs
