- name: print satel diff
  template:
    src: satel.yaml.j2
    dest: config/satel.yaml
  check_mode: true
  diff: true
  register: satel_diff

- name: confirm satel upload
  pause:
    prompt: "Satel config changed, upload? [y/N]"
  when: satel_diff.changed
  register: satel_confirmation

- name: upload satel config
  template:
    src: satel.yaml.j2
    dest: config/satel.yaml
  when: satel_confirmation.user_input is defined and (satel_confirmation.user_input | lower)  == 'y'
