global:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'haos'
    metrics_path: '/api/prometheus'
    static_configs:
      - targets: ['haos.honolulu.org:8123']
