blueprint:
  name: Entity on notifier
  domain: automation
  input:
    entity_id:
      name: Entity ID
      selector:
        entity:
    entity_name:
      name: Entity name
      selector:
        text:
    in_state_time:
      name: Time spent in on state
      selector:
        duration:
    url_to_open:
      name: URL to be opened
      selector:
        text:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input entity_id
    to: "on"

action:
  - variables:
      entity_id: !input entity_id
      entity_name: !input entity_name
      url_to_open: !input url_to_open
  - wait_for_trigger:
      - trigger: state
        entity_id: !input entity_id
        to: "off"
    timeout: !input in_state_time
    continue_on_timeout: true
  - if:
      condition: state
      entity_id: !input entity_id
      state: "on"
    then:
      - action: notify.notify
        data:
          message: "{{ entity_name }}"
          title: "Sprawdź urządzenie"
          data:
            clickAction: "{{ url_to_open }}"
            tag: "entity_on_{{ entity_id }}"
      - wait_for_trigger:
        - trigger: state
          entity_id: !input entity_id
          to: "off"
      - action: notify.notify
        data:
          message: "clear_notification"
          data:
            tag: "entity_on_{{ entity_id }}"
