blueprint:
  name: Light switch mapping
  domain: automation
  input:
    light_switch_input:
      name: Light switch input
      selector:
        entity:
          domain: light
    light_switch_output:
      name: Light switch output
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input light_switch_input
    from: "off"
    to: "on"

action:
  - alias: "Toggle the light"
    service: light.toggle
    target:
      entity_id: !input light_switch_output
