blueprint:
  name: Set blind manually managed
  domain: automation
  input:
    blind:
      name: Blind
      selector:
        entity:
          domain: cover
    delay:
      name: Delay to wait before resetting
      selector:
        time:
      default: "01:00:00"
    blind_manually_managed:
      name: Blind manually managed
      selector:
        entity:
          domain: input_boolean
    close_script:
      name: Closing script
      selector:
        entity:
          domain: script
    open_script:
      name: Opening script
      selector:
        entity:
          domain: script
    auto_script:
      name: Auto position script
      selector:
        entity:
          domain: script

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: cover
      service: open_cover
      service_data:
        entity_id: !input blind
  - platform: event
    event_type: call_service
    event_data:
      domain: cover
      service: close_cover
      service_data:
        entity_id: !input blind
  - platform: event
    event_type: call_service
    event_data:
      domain: cover
      service: set_cover_position
      service_data:
        entity_id: !input blind

action:
  - variables:
      input_blind: !input blind
      input_blind_id: "{{ input_blind.split('.')[1] }}"
  - if:
    - condition: template
      value_template: "{{ is_state('input_boolean.' + input_blind_id, 'on') }}"
    then:
    - action: input_boolean.turn_off
      target:
        entity_id: "input_boolean.{{ input_blind_id }}_set_cover_position_by_script"
    else:
    - action: input_boolean.turn_on
      target:
        entity_id: !input blind_manually_managed
    - delay: !input delay
    - action: input_boolean.turn_off
      target:
        entity_id: !input blind_manually_managed
