blueprint:
  name: Set blind manually managed
  domain: automation
  input:
    blind:
      name: Blind
      selector:
        entity:
          domain: cover
    delay:
      name: Delay to wait before resetting
      selector:
        time:
      default: "01:00:00"
    blind_manually_managed:
      name: Blind manually managed
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input blind

action:
  - variables:
      input_blind: !input blind
      input_blind_id: "{{ input_blind.split('.')[1] }}"
  - if:
    - condition: template
      value_template: "{{ is_state('input_boolean.' + input_blind_id + '_set_cover_position_by_script', 'on') }}"
    then:
      - delay: !input delay
      - action: input_boolean.turn_off
        target:
          entity_id: "input_boolean.{{ input_blind_id }}_set_cover_position_by_script"
    else:
      - action: input_boolean.turn_on
        target:
          entity_id: !input blind_manually_managed
