light_switches:
  - device_id: office_light_switch
    friendly_name: Gabinet światło
    area_id: office
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        name: Biurko Piotrka
      - id: L2
        suffix: _l2
        name: Biurko Moniki

  - device_id: "downstairs_bathroom_main_light_switch"
    friendly_name: Dolna łazienka górne światło
    area_id: downstairs_bathroom
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Dolna łazienka górne światło

  - device_id: "downstairs_bathroom_mirror_light_switch"
    friendly_name: Dolna łazienka oświetlenie lustra
    area_id: downstairs_bathroom
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Dolna łazienka oświetlenie lustra

  - device_id: "living_room_light_switch"
    friendly_name: Salon światło
    area_id: living_room
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix:
        name: Salon

  - device_id: dining_room_light_switch
    friendly_name: Jadalnia światło
    area_id: living_room
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix:
        name: Jadalnia

  - device_id: "next_to_stairs_light_switch"
    friendly_name: Światło przed schodami
    area_id: living_room
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Światło przed schodami

  - device_id: "tv_backlight_light_switch"
    friendly_name: Podświetlenie TV
    area_id: living_room
    dimmable: false
    floor: downstairs
    parts:
      - id: L1
        suffix:
        name: Podświetlenie TV

  - device_id: "pantry_light_switch"
    friendly_name: Spiżarnia światło
    area_id: living_room
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix:
        name: Spiżarnia światło

  - device_id: "kitchen_main_light_switch"
    friendly_name: Kuchnia górne światło
    area_id: kitchen
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Kuchnia górne światło

  - device_id: "kitchen_countertop_light_switch"
    friendly_name: Kuchnia oświetlenie barku
    area_id: kitchen
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Kuchnia oświetlenie barku

  - device_id: "mudroom_light_switch"
    friendly_name: Wiatrołap światło
    area_id: mudroom
    dimmable: true
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        name: Wiatrołap górne światło
      - id: L2
        suffix: _l2
        name: Wiatrołap oświetlenie szafek

  - device_id: "mudroom_auxiliary_light_switch"
    friendly_name: Wiatrołap - przycisk pomocniczy
    dimmable: false
    area_id: mudroom
    floor: downstairs
    parts:
      - id: L1
        suffix:
        technical: true
        name: Przycisk pomocniczy

  - device_id: "garage_light_switch"
    friendly_name: Garaż światło
    area_id: garage
    dimmable: false
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        name: Garaż światło przy kotłowni
      - id: L2
        suffix: _l2
        name: Garaż światło przy wiatrołapie

  - device_id: "boiler_room_light_switch"
    friendly_name: Kotłownia światło
    area_id: boiler_room
    dimmable: false
    floor: downstairs
    parts:
      - id: L1
        suffix: _l1
        technical: true
        name: Przycisk pomocniczy
      - id: L2
        suffix: _l2
        name: Kotłownia światło

  - device_id: "staircase_light_switch"
    friendly_name: Światło na schodach
    area_id: staircase
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło na schodach

  - device_id: "laundry_room_light_switch"
    friendly_name: Światło w pralni
    area_id: laundry_room
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło w pralni

  - device_id: "upstairs_bathroom_main_light_switch"
    friendly_name: Górna łazienka światło górne
    area_id: upstairs_bathroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Górna łazienka światło górne
      - id: L2
        suffix: _l2
        name: Górna łazienka LED pod prysznicem
        dimmable: false

  - device_id: "upstairs_bathroom_left_mirror_light_switch"
    friendly_name: Górna łazienka światło przy lewym lustrze
    area_id: upstairs_bathroom
    dimmable: false
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Górna łazienka światło przy lewym lustrze górne
      - id: L2
        suffix: _l2
        name: Górna łazienka światło przy lewym lustrze LED

  - device_id: "upstairs_bathroom_right_mirror_light_switch"
    friendly_name: Górna łazienka światło przy prawym lustrze
    area_id: upstairs_bathroom
    dimmable: false
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Górna łazienka światło przy prawym lustrze LED
      - id: L2
        suffix: _l2
        name: Górna łazienka światło przy prawym lustrze górne

  - device_id: "upstairs_bathroom_washbasin_cabinet_backlight"
    friendly_name: Górna łazienka podświetlenie szafki z umywalkami
    area_id: upstairs_bathroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Górna łazienka podświetlenie szafki z umywalkami

  - device_id: "guest_room_light_switch"
    friendly_name: Światło w gościnnym
    area_id: guest_room
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło w gościnnym

  - device_id: "junk_room_light_switch"
    friendly_name: Światło w schowku
    area_id: junk_room
    dimmable: false
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło w schowku

  - device_id: "master_bedroom_main_light_switch"
    friendly_name: Główne światło w głównej sypialni
    area_id: master_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Główne światło w głównej sypialni

  - device_id: "master_bedroom_over_bed_light_switch"
    friendly_name: Oświetlenie nad łóżkiem w głównej sypialni
    area_id: master_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Oświetlenie nad łóżkiem w głównej sypialni

  - device_id: "master_bedroom_bed_backlight_light_switch"
    friendly_name: Podświetlenie łóżka w głównej sypialni
    area_id: master_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Podświetlenie łóżka w głównej sypialni

  - device_id: "walk_in_wardrobe_light_switch"
    friendly_name: Światło w garderobie
    area_id: master_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Podświetlenie LED w garderobie
      - id: L2
        suffix: _l2
        name: Górne światło w garderobie

  - device_id: "west_bedroom_light_switch"
    friendly_name: Światło w zachodniej sypialni
    area_id: west_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Światło z tyłu w zachodniej sypilani
      - id: L2
        suffix: _l2
        name: Światło przy wejściu w zachodniej sypilani

  - device_id: "south_bedroom_light_switch"
    friendly_name: Światło w południowej sypialni
    area_id: south_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło w południowej sypilani

  - device_id: "east_bedroom_light_switch"
    friendly_name: Światło we wschodniej sypialni
    area_id: east_bedroom
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix: _l1
        name: Światło z tyłu we wschodniej sypilani
      - id: L2
        suffix: _l2
        name: Światło przy wejściu we wschodniej sypilani

  - device_id: "hallway_light_switch"
    friendly_name: Światło w korytarzu
    area_id: hallway
    dimmable: true
    floor: upstairs
    parts:
      - id: L1
        suffix:
        name: Światło w korytarzu

  - device_id: "attic_light_switch"
    friendly_name: Światło na strychu
    area_id: attic
    dimmable: false
    floor: attic
    parts:
      - id: L1
        suffix:
        name: Światło na strychu

  - device_id: "front_door_light_switch"
    friendly_name: Światło przed drzwiami wejściowymi
    area_id: outdoors
    dimmable: false
    floor: outdoors
    parts:
      - id: L1
        suffix:
        name: Światło przed drzwiami wejściowymi

  - device_id: "side_door_light_switch"
    friendly_name: Światło przed drzwiami bocznymi
    area_id: outdoors
    dimmable: false
    floor: outdoors
    parts:
      - id: L1
        suffix:
        name: Światło przed drzwiami bocznymi

temporary_lights:
  - id: garage_temporary_light
    friendly_name: Tymczasowe światło - garaż
    input: binary_sensor.garage_gate_magnetic_sensor
    entities:
      - light.garage_light_switch_l1
      - light.garage_light_switch_l2
    timeout_seconds: 300
  - id: mudroom_temporary_light
    friendly_name: Tymczasowe światło - wiatrołap
    input: binary_sensor.mudroom_motion_sensor
    entities:
      - light.mudroom_light_switch_l2
    timeout_seconds: 180
  - id: upstairs_bathroom_washbasin_cabinet_temporary_light
    friendly_name: Tymczasowe światło - podświetlenie pod umywalkami w górnej łazience
    input: binary_sensor.upstairs_bathroom_motion_sensor
    entities:
      - light.upstairs_bathroom_washbasin_cabinet_backlight
    timeout_seconds: 180

light_switch_mappings:
  - name: next_to_stairs
    from:
      device_id: next_to_stairs_light_switch
      part_id: L1
    to:
      - device_id: dining_room_light_switch
        part_id: L1

  - name: downstairs_bathroom_main
    from:
      device_id: downstairs_bathroom_main_light_switch
      part_id: L1
    to:
      - device_id: downstairs_bathroom_mirror_light_switch
        part_id: L2

  - name: downstairs_bathroom_mirror
    from:
      device_id: downstairs_bathroom_mirror_light_switch
      part_id: L1
    to:
      - device_id: downstairs_bathroom_main_light_switch
        part_id: L2

  - name: kitchen_countertop
    from:
      device_id: kitchen_countertop_light_switch
      part_id: L1
    to:
      - device_id: "kitchen_main_light_switch"
        part_id: L2

  - name: kitchen_main
    from:
      device_id: "kitchen_main_light_switch"
      part_id: L1
    to:
      - device_id: "kitchen_countertop_light_switch"
        part_id: L2

  - name: mudroom_wardrobe
    from:
      device_id: "mudroom_auxiliary_light_switch"
      part_id: L1
    to:
      - device_id: "mudroom_light_switch"
        part_id: L2

  - name: boiler_room
    from:
      device_id: "boiler_room_light_switch"
      part_id: L1
    to:
      - device_id: "garage_light_switch"
        part_id: L1
      - device_id: "garage_light_switch"
        part_id: L2
