blueprint:
  name: Light switch double click
  domain: automation
  input:
    light_switch:
      name: Light switch
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input light_switch
    from: "on"
    to: "off"

action:
  - variables:
      light_switch_id: !input light_switch # to use in templates
  - alias: "Wait for second click"
    wait_template: "{{ is_state(light_switch_id, 'on') }}"
    timeout: 2
  - if:
      condition: template
      value_template: "{{ wait.completed }}"
    then:
      - service: light.turn_on
        target:
          entity_id: !input light_switch
        data:
          brightness: 255
