{
 "title": "Energia",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Zużyta energia w 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(haos_sensor_energy_kwh[24h])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Zużyta energia w 30 dni",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(haos_sensor_energy_kwh[30d])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Całkowita zużyta energia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "haos_sensor_energy_kwh", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Pobór mocy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "haos_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  }
 ]
}