{
 "title": "Satel",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "custom_interval",
    "query": "1m, 2m, 3m, 5m, 15m, 1h, 2h, 3h, 6h, 12h, 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Aktywacja czujek ruchu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(haos_state_change_total{entity=~\".*motion_sensor\"}[$custom_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Aktywacja kontaktronów - wejścia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(haos_state_change_total{entity=~\".*(door|garage_gate)_magnetic_sensor\"}[$custom_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Aktywacja kontaktronów - okna",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(haos_state_change_total{entity=~\".*window_magnetic_sensor\"}[$custom_interval])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}